### ISSUE TITLE
Consider moving the repository to MakieOrg

### ISSUE THREAD

**Issue by juliohm** [stelmo/TernaryDiagrams.jl#9]
https://github.com/MakieOrg

**Comment by stelmo** [comment]
Hi there! Unfortunately, I don't think this recipe is good enough to go there :) It is quite hacky, the best solution would be to create a new axis specifically for ternary plots. I am considering delving into the internals of Makie to do this, but likely not within the next month. I will advertise the package on discourse (once it is registered) for people that need a quick ternary plot "fix" in the mean time!

**Comment by juliohm** [comment]
Got it. Thanks for the initiative, ternary axes are very welcome!
